services:
  db:
    image: postgres:15

  web_django:
    image: miapp
    command: gunicorn Tienda.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  pagos_flask:
    image: flaskapp
    ports:
      - "5000:5000"

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web_django
      - pagos_flask